version: '3.7'

services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  auth:
    # restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c "
    #   python /auth_service/manage.py makemigrations
    #   && python /auth_service/manage.py migrate
    #   && python /auth_service/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/auth_service
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: